export const fitnessQuotes: [string, string][] = [
  ["Stronger than yesterday. Hungrier for tomorrow.", "Kal se zyada strong, kal ke liye taiyaar."],
  ["Discipline shows up when motivation sleeps.", "Motivation soye, discipline jaage."],
  ["My only competition is my last rep.", "Mera competition meri pichhli rep hai."],
  ["Building strength, not excuses.", "Bahane nahi, taqat bana raha hoon."],
  ["Progress isn't loud. It's consistent.", "Taraqqi shor nahi, consistency maangti hai."],
  ["Lift with intention. Recover with respect.", "Mehnat bhi zaroori, aaram bhi."],
  ["The strongest flex is showing up again.", "Asli flex roz lautna hai."],
  ["Small reps. Big changes.", "Chhoti reps, bade badlav."],
  ["Rest days are part of the plan.", "Aaram bhi training ka hissa hai."],
  ["Not chasing a body. Building a life.", "Sirf body nahi, zindagi bana raha hoon."],
  ["पसीने की हर बूंद, खुद से किया एक वादा है।", "Every drop of sweat is a promise to myself."],
  ["ताकत सिर्फ मांसपेशियों में नहीं, इरादों में होती है।", "Strength lives in intentions, not just muscles."],
  ["आज की मेहनत, कल की ताकत।", "Today's effort, tomorrow's strength."],
  ["अपनी रफ्तार से चलो, बस रुकना मत।", "Move at your own pace; keep going."],
  ["वजन उठाने से पहले, अपने डर को उतारो।", "Put down your fear before picking up the weights."],
  ["हर दिन रिकॉर्ड नहीं, कुछ दिन सिर्फ कोशिश होती है।", "Not every day is a record; some days are simply effort."],
  ["Gym mera reset button hai.", "The gym is my reset button."],
  ["Mirror se pehle mindset badla.", "The mindset changed before the mirror did."],
  ["Aaj thoda mushkil, kal thoda strong.", "A little harder today, a little stronger tomorrow."],
  ["Apni journey, apni pace, apni jeet.", "My journey, my pace, my victory."],
  ["Fitness ek finish line nahi, roz ka faisla hai.", "Fitness isn't a finish line; it's a daily decision."],
  ["Heavy weights, halka stress.", "Heavy weights, lighter worries."],
  ["Consistency ka result filter se nahi milta.", "No filter can replace consistency."],
  ["Body ko train karo, khud se pyaar bhi karo.", "Train your body and be kind to yourself."],
];