// KP's Captions, Quotes & Hashtags — internal caption database
// Each entry: [caption text, translation / companion line]

export type RawQuote = [text: string, translation: string];

export const quotesByCategory: Record<string, RawQuote[]> = {
  Attitude: [
    ["मेरी पहचान मेरे काम से है, नाम से नहीं।", "I'm known by my work, not my name."],
    ["Main trend follow nahi karta, trend banata hoon.", "I don't follow trends, I set them."],
    ["Silence is my attitude, success is my answer.", "Khamoshi mera attitude, kamyabi mera jawab."],
    ["शेर अकेला चलता है, भीड़ भेड़ों की होती है।", "Lions walk alone; crowds are for sheep."],
    ["मेरा अंदाज़ ही मेरी पहचान है, इसे बदलने की कोशिश मत करना।", "My attitude is my identity—don't try to change it."],
    ["Attitude mera weakness nahi, signature hai.", "My attitude isn't a weakness, it's my signature."],
    ["जो लोग मुझसे जलते हैं, वो खुद को जलाते हैं।", "Those who burn with jealousy only burn themselves."],
    ["Main woh hoon jise log ignore karke regret karte hain.", "I'm the one people regret ignoring."],
    ["खामोश रहना मेरी कमज़ोरी नहीं, मेरा इंतज़ार है।", "My silence isn't weakness—it's patience."],
    ["Born to express, not to impress.", "जीने के लिए पैदा हुआ हूँ, दिखाने के लिए नहीं।"],
    ["मेरी सोच मेरी हद है, तुम्हारी समझ से परे।", "My thinking is my limit—beyond your understanding."],
    ["Log kehte hain main badal gaya, sach ye hai main samajh gaya.", "People say I've changed; the truth is I've understood."],
    ["जिस दिन मैंने जवाब देना शुरू किया, उस दिन लोग सवाल करना भूल गए।", "The day I started answering, people forgot how to question."],
    ["My vibe attracts my tribe.", "मेरी सोच ही मेरी दुनिया बनाती है।"],
    ["अपने स्तर पर खेलो, मेरे स्तर की कल्पना मत करो।", "Play at your level; don't imagine mine."],
    ["Respect kamai jaati hai, maangi nahi jaati.", "Respect is earned, never begged for."],
    ["मैं किताब नहीं हूँ कि हर कोई मुझे पढ़ ले।", "I'm not a book that everyone can read."],
    ["Silence is my attitude, action is my answer.", "खामोशी मेरा अंदाज़ है, काम मेरा जवाब।"],
    ["जो मुझे नहीं जानता, वो मुझ पर राय नहीं दे सकता।", "Those who don't know me can't judge me."],
    ["Apna style itna alag hai ki copy karne walon ko bhi sharam aaye.", "My style is so unique even imitators feel shy."],
    ["मैं हार नहीं मानता, बस रुक जाता हूँ सही वक़्त के लिए।", "I don't give up; I just pause for the right time."],
    ["Confidence level: main khud apna competition hoon.", "I'm my own competition."],
    ["दुश्मनों की कमी नहीं है, बस हम्मत की कमी है उनमें।", "There's no shortage of enemies—just of courage in them."],
    ["I don't chase, I attract.", "मैं भागता नहीं, खिंचता हूँ।"],
    ["मेरे बारे में सोचना बंद करो, अपने बारे में सोचो।", "Stop thinking about me; think about yourself."],
    ["Jigar wala hoon, jhukne wala nahi.", "I have heart, not the habit of bowing."],
    ["मेरी कद्र उनसे करवाओ जिन्हें कद्र करनी आती है।", "Let those who understand value do the valuing."],
    ["Rules tode nahi jaate, mujhse banaye jaate hain.", "Rules aren't broken by me—they're made by me."],
    ["अपनी औकात में रहो, मेरी नज़र में रहोगे।", "Stay in your limits to stay in my sight."],
    ["I'm not special, I'm limited edition.", "मैं खास नहीं, दुर्लभ हूँ।"],
    ["जो हँसता था मेरी हार पर, अब ताली बजाता है मेरी जीत पर।", "Those who laughed at my loss now clap at my win."],
    ["Mera naam hi kaafi hai, pehchan ki zarurat nahi.", "My name alone is enough—no introduction needed."],
    ["दुनिया जलती है तो जलने दो, हम चलते हैं अपने रस्ते।", "Let the world burn with envy; we walk our own path."],
    ["Ego nahi hai, self-respect hai — farak samjho.", "It's not ego, it's self-respect—know the difference."],
    ["मैं वो किरदार हूँ जिसे लिखना आसान है, जीना नहीं।", "I'm a character easy to write, hard to live."],
    ["Bad attitude? Nahi, bas badhiya standards hain.", "Not a bad attitude—just high standards."],
    ["मुझे पसंद करना मुश्किल है, क्योंकि मैं सबके लिए नहीं बना।", "Liking me is hard because I wasn't made for everyone."],
    ["Legends don't compete, they dominate.", "दिग्गज मुकाबला नहीं करते, राज करते हैं।"],
    ["मेरी खुशी मेरा हथियार है, इसे छीनने की कोशिश मत करना।", "My happiness is my weapon—don't try to snatch it."],
    ["Jo samne bolta hai woh dost, jo peeth peeche bolta hai woh chapter khatam.", "Who speaks to my face is a friend; behind my back is a closed chapter."],
    ["मैं किसी की नकल नहीं, मैं अपना ओरिजिनल हूँ।", "I'm nobody's copy—I'm my own original."],
    ["Swag mera default setting hai.", "My swag is my default setting."],
    ["जिन्हें मुझसे परेशानी है, उन्हें अपनी सोच बदलनी चाहिए।", "Those bothered by me should change their thinking."],
    ["I don't follow trends, I set them.", "मैं चलन नहीं अपनाता, चलन बनाता हूँ।"],
    ["मेरा सर कभी नहीं झुकता, सिवाय माँ के आशीर्वाद के।", "My head bows only for my mother's blessing."],
    ["Haters meri motivation hain, unke bina story adhuri hai.", "Haters are my motivation—without them the story is incomplete."],
    ["मैं अकेला हूँ, कमज़ोर नहीं।", "I'm alone, not weak."],
    ["Classy, sassy, aur thoda sa nasty.", "Classy, sassy, and a little bit savage."],
    ["जो मुझे रोकने आए, वो खुद रुक गए।", "Those who came to stop me stopped themselves."],
    ["My life, my rules, my attitude.", "मेरी ज़िंदगी, मेरे उसूल, मेरा अंदाज़।"],
    ["दिल का अच्छा हूँ, दिमाग का खतरनाक।", "Good at heart, dangerous in mind."],
    ["Kamyabi meri behen hai, usse milne ke liye appointment lo.", "Success is my sister—take an appointment to meet her."],
    ["मैं वो सवाल हूँ जिसका जवाब तुम्हारे पास नहीं।", "I'm the question you have no answer to."],
    ["Attitude ka volume full, duniya ka drama mute.", "Attitude on full volume, world's drama on mute."],
    ["मैं जैसा हूँ वैसा ही सही हूँ, बदलना तुम्हारा काम है।", "I'm right as I am; changing is your job."],
    ["Be yourself — baaki sab already taken hain.", "अपने आप बनो — बाकी सब पहले से भरे हैं।"],
    ["मेरे सपने मेरे क़द से बड़े हैं, इसीलिए झुकता नहीं।", "My dreams are taller than me—that's why I never bow."],
  ],
  "Instagram Reels": [
    ["Reel life on, real life strong.", "Reel bhi, real bhi."],
    ["POV: tum meri reel dekh ke smile kar rahe ho.", "POV: you're smiling at my reel."],
    ["वाइब मैच हो तो फॉलो कर लो।", "If the vibe matches, hit follow."],
    ["Plot twist: main hi main character hoon.", "Plot twist: I'm the main character."],
    ["Main apni khud ki story likhta hoon, tum bas page turn karo.", "I write my own story, you just turn the page."],
    ["Reel bana rahe hain, sapne nahi — lekin dono viral honge.", "Making reels, not dreams—but both will go viral."],
    ["कैमरा ऑन है तो दिल भी ऑन है।", "When the camera is on, the heart is on too."],
    ["POV: Tum meri reel dekh rahe ho aur main tumhari life badal raha hoon.", "POV: You're watching my reel and I'm changing your life."],
    ["15 second ki reel, 15 saal ki mehnat.", "A 15-second reel, 15 years of hard work."],
    ["Trend follow nahi karta, trend banata hoon.", "I don't follow trends, I create them."],
    ["ये सिर्फ वीडियो नहीं, मेरी मेहनत का ट्रेलर है।", "This isn't just a video—it's the trailer of my hard work."],
    ["Scroll mat karo, feel karo.", "Don't scroll, feel it."],
    ["Reels chal rahi hain, sapne bhi chal rahe hain.", "Reels are running, and so are my dreams."],
    ["एक रील जो दिल छू जाए, वो वायरल हो ही जाती है।", "A reel that touches the heart goes viral on its own."],
    ["Camera, confidence, aur thoda sa content — bas yahi formula hai.", "Camera, confidence, and a little content—that's the formula."],
    ["Viral hona luck nahi, consistency hai.", "Going viral isn't luck, it's consistency."],
    ["मेरी रील देखो, मेरी कहानी समझो।", "Watch my reel, understand my story."],
    ["No filter, no fake — sirf real vibe.", "No filter, no fake—just real vibes."],
    ["आज का कंटेंट, कल का क्रेज़।", "Today's content, tomorrow's craze."],
    ["Har reel ek message hai, samajhne walon ke liye.", "Every reel is a message for those who understand."],
    ["Views aate jaate hain, impact reh jaata hai.", "Views come and go; impact stays."],
    ["मैं कंटेंट नहीं बनाता, मैं यादें बनाता हूँ।", "I don't create content, I create memories."],
    ["Reel it till you feel it.", "जब तक महसूस न हो, रील बनाते रहो।"],
    ["Ek reel roz, demag ko roz naya dose.", "One reel a day keeps the boredom away."],
    ["लोग पूछते हैं कंटेंट कहाँ से आता है — ज़िंदगी से, भाई।", "People ask where content comes from—from life, brother."],
    ["Transition itni smooth ki life bhi jealous hai.", "Transitions so smooth even life is jealous."],
    ["मेरी रील का बजट कम है, जज़्बा ज़्यादा।", "My reel's budget is small, the passion is huge."],
    ["FYP pe aana destiny nahi, strategy hai.", "Landing on FYP isn't destiny, it's strategy."],
    ["सिर्फ देखने वालों के लिए नहीं, सीखने वालों के लिए।", "Not just for watchers—for learners."],
    ["Content is king, consistency is queen.", "कंटेंट राजा है, निरंतरता रानी।"],
    ["Aaj reel, kal brand deal.", "Reels today, brand deals tomorrow."],
    ["मेरा फोन ही मेरा स्टूडियो है।", "My phone is my studio."],
    ["Like karo ya na karo, reel toh banti rahegi.", "Like it or not, the reels will keep coming."],
    ["Yeh vibe sirf reel pe milti hai, real mein nahi.", "This vibe exists only on reels, not in real life."],
    ["हर स्क्रॉल के पीछे एक कहानी है, ये मेरी है।", "Behind every scroll is a story—this one is mine."],
    ["Slow motion mein bhi fast growth.", "Fast growth even in slow motion."],
    ["मेरी रील में वो बात है जो किताबों में नहीं मिलती।", "My reels have what books don't."],
    ["Editing meri art hai, camera mera dil.", "Editing is my art, the camera my heart."],
    ["Viral reel ka secret? Sach bolna, style se.", "The secret of a viral reel? Telling the truth, with style."],
    ["Reel banai thi timepass ke liye, ab passion ban gayi.", "Started reels for fun; now they're my passion."],
    ["हर व्यू एक वोट है, हर शेयर एक जीत।", "Every view is a vote, every share a win."],
    ["Main reel nahi, revolution bana raha hoon.", "I'm not making reels, I'm starting a revolution."],
    ["Audio trending tha, maine use legendary bana diya.", "The audio was trending; I made it legendary."],
    ["कंटेंट क्रिएटर हूँ, सपनों का इंजीनियर हूँ।", "I'm a content creator—an engineer of dreams."],
    ["One take wonder — kyunki retake ka time nahi hai.", "One-take wonder—no time for retakes."],
    ["मेरी रील देखकर लोग मुस्कुराते हैं, यही मेरी कमाई है।", "People smile watching my reels—that's my earning."],
    ["Algorithm se dosti nahi, audience se pyaar chahiye.", "I don't need the algorithm's friendship, just the audience's love."],
    ["Reels meri diary hain, public diary.", "My reels are my diary—a public one."],
    ["हर दिन एक नई रील, हर रील एक नया सबक।", "A new reel every day, a new lesson in every reel."],
    ["Camera ke saamne jhooth nahi bolta, isliye sach dikhta hai.", "I don't lie in front of the camera—that's why the truth shows."],
    ["Meri reel ka budget? Zero. Confidence? Unlimited.", "My reel budget? Zero. Confidence? Unlimited."],
    ["जो दिखता है वो बिकता है, जो छूता है वो टिकता है।", "What is seen sells; what is felt lasts."],
    ["Reel life bhi real life jaisi hai — bas thodi zyada filmy.", "Reel life is like real life—just a bit more filmy."],
    ["Shoot, edit, post, repeat — yahi meri zindagi hai.", "Shoot, edit, post, repeat—that's my life."],
    ["मेरा कंटेंट मेरा क्रेडिट कार्ड है — हर जगह चलता है।", "My content is my credit card—accepted everywhere."],
    ["Viral hone ka formula? Apne aap ko viral hone do.", "The formula for going viral? Let yourself go viral."],
  ],
  Romantic: [
    ["तुम मेरी हर दुआ का जवाब हो।", "You are the answer to all my prayers."],
    ["You're my favourite notification.", "Tum meri favourite notification ho."],
    ["Tere saath har pal Sunday lagta hai.", "Every moment with you feels like Sunday."],
    ["दिल ने कहा, बस तुम ही काफ़ी हो।", "My heart said, you're enough."],
    ["तुम पास हो तो हर लम्हा थोड़ा और खूबसूरत लगता है।", "Every moment feels more beautiful when you're near."],
    ["Tere bina adhuri si hai har subah, har shaam.", "Without you, every morning and evening feels incomplete."],
    ["मोहब्बत लफ़्ज़ों में नहीं, नज़रों में होती है।", "Love lives not in words but in glances."],
    ["You are my favorite notification.", "तुम मेरी सबसे प्यारी नोटिफिकेशन हो।"],
    ["तेरी हँसी मेरी सबसे प्यारी धुन है।", "Your laughter is my favorite melody."],
    ["Dil ne tumse jo baat ki, lafzon tak na aa saki.", "What my heart told you, words could never reach."],
    ["तुमसे मिलकर लगा, जैसे किस्मत ने मुझे चुन लिया।", "Meeting you felt like destiny chose me."],
    ["Pyaar woh nahi jo duniya ko dikhaye, pyaar woh hai jo dil se nibhaye.", "Love isn't what you show the world; it's what you honor from the heart."],
    ["तेरे नाम से शुरू होती है मेरी हर दुआ।", "Every prayer of mine begins with your name."],
    ["I fell for you the way rain falls — naturally and completely.", "मैं तुमसे ऐसे मोहब्बत कर बैठा जैसे बारिश होती है — अपने आप और पूरी तरह।"],
    ["तुम मेरी ज़िंदगी का वो पन्ना हो जिसे मैं बार-बार पढ़ना चाहता हूँ।", "You're the page of my life I want to read again and again."],
    ["Tera haath thaame chalna hi meri manzil hai.", "Walking while holding your hand is my destination."],
    ["इश्क़ में पड़ना आसान है, निभाना मुश्किल — और मैं निभा रहा हूँ।", "Falling in love is easy; keeping it is hard—and I'm keeping it."],
    ["Every love story is beautiful, but ours is my favorite.", "हर मोहब्बत की कहानी खूबसूरत है, पर हमारी मेरी पसंदीदा है।"],
    ["तेरी आँखों में वो सुकून है जो कहीं और नहीं मिलता।", "Your eyes hold a peace I find nowhere else."],
    ["Tum paas ho toh door koi bhi faasla nahi lagta.", "When you're near, no distance feels far."],
    ["मोहब्बत का मौसम नहीं होता, मोहब्बत ही मौसम होती है।", "Love has no season—love itself is the season."],
    ["With you, even silence feels like a conversation.", "तुम्हारे साथ खामोशी भी बातचीत जैसी लगती है।"],
    ["तू मेरी आदत नहीं, मेरी ज़रूरत है।", "You're not my habit—you're my need."],
    ["Dil ka corner office tumhare naam.", "The corner office of my heart is reserved for you."],
    ["तुम्हारे बिना ये दिल बस धड़कता है, जीता नहीं।", "Without you, this heart only beats—it doesn't live."],
    ["Pyaar mein logic nahi, magic chalta hai.", "In love, it's not logic but magic that works."],
    ["तेरी एक मुस्कान मेरे पूरे दिन की बैटरी चार्ज कर देती है।", "One smile of yours charges my whole day."],
    ["I want to be your favorite hello and hardest goodbye.", "मैं तुम्हारा सबसे प्यारा 'हैलो' और सबसे मुश्किल 'अलविदा' बनना चाहता हूँ।"],
    ["तुम वो कविता हो जिसे मैंने कभी लिखा नहीं, पर हमेशा महसूस किया।", "You're the poem I never wrote but always felt."],
    ["Mohabbat mein jeet haar nahi hoti, sirf saath hota hai.", "In love there's no win or loss—only togetherness."],
    ["तेरे इश्क़ में डूबना ही मेरी तैराकी है।", "Drowning in your love is my way of swimming."],
    ["Home is wherever I'm with you.", "घर वहीं है जहाँ तुम हो।"],
    ["तुम्हारी बाहों में वक़्त रुक जाता है।", "Time stops in your arms."],
    ["Ishq woh aag hai jo jalati nahi, roshan karti hai.", "Love is a fire that doesn't burn—it illuminates."],
    ["तुम मेरे सपनों की सबसे सच्ची हकीकत हो।", "You're the truest reality of my dreams."],
    ["Tere liye main chaand taare nahi, pura aasmaan maang lunga.", "For you, I won't ask for the moon and stars—I'll ask for the whole sky."],
    ["मोहब्बत एक बार हुई थी, और हर बार तुमसे ही होती है।", "I fell in love once, and it happens with you every time."],
    ["You + Me = My favorite equation.", "तुम + मैं = मेरा पसंदीदा गणित।"],
    ["तेरी यादें मेरी रातों की रोशनी हैं।", "Your memories are the light of my nights."],
    ["Dil ki gehraiyon mein sirf tumhara naam likha hai.", "Only your name is written in the depths of my heart."],
    ["तुमसे बात करके लगता है जैसे दिल ने साँस ली हो।", "Talking to you feels like my heart took a breath."],
    ["Love isn't finding someone to live with — it's finding someone you can't live without.", "मोहब्बत किसी के साथ जीना नहीं — किसी के बिना न जी पाना है।"],
    ["तेरे बिना अधूरा हूँ, तेरे साथ पूरा।", "Incomplete without you, complete with you."],
    ["Meri har subah ka alarm tumhara khayal hai.", "My every morning's alarm is the thought of you."],
    ["तुम वो गाना हो जो मैं repeat पर सुनता हूँ।", "You're the song I keep on repeat."],
    ["Ishq mein padh gaya hoon itna, ki ab uthna nahi chahta.", "I've fallen so deep in love that I don't want to get up."],
    ["तेरी खुशी में ही मेरी खुशी छुपी है।", "My happiness hides inside yours."],
    ["Falling for you wasn't a choice, it was destiny.", "तुमसे मोहब्बत मेरा फैसला नहीं, मेरी किस्मत थी।"],
    ["तुम्हारा हाथ पकड़कर लगता है पूरी दुनिया पकड़ ली।", "Holding your hand feels like holding the whole world."],
    ["Tum meri zindagi ka wo chapter ho jo kabhi khatam na ho.", "You're the chapter of my life that never ends."],
    ["मोहब्बत शब्दों की मोहताज नहीं, एहसासों की होती है।", "Love doesn't depend on words—it lives in feelings."],
    ["My heart beats in your name's rhythm.", "मेरा दिल तुम्हारे नाम की ताल पर धड़कता है।"],
    ["तेरे साथ बिता हर पल, मेरी सबसे कीमती दौलत है।", "Every moment with you is my most precious wealth."],
    ["Pyar ek ehsaas hai, aur tum mera sabse bada ehsaas ho.", "Love is a feeling, and you are my biggest one."],
    ["तुम्हारी एक झलक के लिए ये दिल हमेशा तरसता है।", "This heart always longs for one glimpse of you."],
    ["Forever chota pad gaya, jab tumse milne ka waqt socha.", "Even 'forever' felt short when I thought of time with you."],
  ],
  Motivation: [
    ["हार मत मानो, शुरुआत हमेशा कठिन होती है।", "Don't give up; beginnings are always hard."],
    ["Grind in silence, let success make the noise.", "Chup chaap mehnat, kamyabi shor machaye."],
    ["Mehnat itni karo ki kismat bhi bol uthe, le le beta.", "Work so hard that luck gives in."],
    ["सपने बड़े रखो, इरादे उससे भी बड़े।", "Dream big, intend bigger."],
    ["Koshish aaj karo, kal ke liye bahane mat chhodna.", "Make the effort today; don't save excuses for tomorrow."],
    ["मेहनत इतनी खामोशी से करो कि कामयाबी शोर मचा दे।", "Work so silently that success makes the noise."],
    ["Dream big, start small, act now.", "बड़े सपने देखो, छोटी शुरुआत करो, अभी कदम उठाओ।"],
    ["जो टूटकर भी नहीं रुके, वही इतिहास बनाते हैं।", "Those who don't stop even after breaking make history."],
    ["Sapne woh nahi jo neend mein aaye, sapne woh hain jo neend uda dein.", "Dreams aren't what you see in sleep; they're what keep you awake."],
    ["हार उसकी होती है जो रुक जाता है, तुम तो चलते रहो।", "Defeat belongs to those who stop—you just keep moving."],
    ["Your only limit is the one you accept.", "तुम्हारी एकमात्र सीमा वही है जिसे तुमने मान लिया।"],
    ["मुश्किलें रास्ते की नहीं, रुकने की निशानी नहीं हैं।", "Difficulties aren't a sign to stop."],
    ["Mehnat ka fal meetha hota hai, bas der se milta hai.", "The fruit of hard work is sweet—it just arrives late."],
    ["कल का इंतज़ार मत करो, आज को कल बना दो।", "Don't wait for tomorrow; turn today into tomorrow."],
    ["Success is 1% luck, 99% showing up every day.", "कामयाबी 1% किस्मत है, 99% रोज़ हाज़िरी लगाना।"],
    ["जिस दिन तुम्हारा 'क्यों' साफ हो जाएगा, 'कैसे' खुद मिल जाएगा।", "The day your 'why' becomes clear, the 'how' will find itself."],
    ["Fall seven times, stand up eight.", "सात बार गिरो, आठवीं बार उठो।"],
    ["दुनिया तब तक नहीं मानती जब तक तुम खुद को नहीं मना लेते।", "The world won't believe you until you convince yourself."],
    ["Struggle aaj ka hai, shohrat kal ki hogi.", "The struggle is today's; the fame will be tomorrow's."],
    ["अपने आप पर भरोसा रखो, बाकी सब अपने आप हो जाएगा।", "Trust yourself; everything else will fall into place."],
    ["Don't stop until you're proud.", "तब तक मत रुको जब तक खुद पर गर्व न हो।"],
    ["मंज़िल उन्हीं को मिलती है जिनके सपनों में जान होती है।", "Destinations belong to those whose dreams have life."],
    ["Waqt sabka aata hai, bas mehnat karnewalon ka pehle aata hai.", "Everyone's time comes—the hardworking get theirs first."],
    ["छोटे कदम भी मंज़िल तक ले जाते हैं, बस रुकना नहीं चाहिए।", "Even small steps reach the goal—just never stop."],
    ["Be so good they can't ignore you.", "इतने अच्छे बनो कि कोई नज़रअंदाज़ न कर सके।"],
    ["आज की मेहनत, कल की मुस्कान है।", "Today's hard work is tomorrow's smile."],
    ["Zindagi ek race nahi, ek journey hai — apni speed se chalo.", "Life isn't a race, it's a journey—walk at your own pace."],
    ["जो दूसरों के लिए नमकीन पसीना है, वही तुम्हारी कामयाबी का स्वाद है।", "The sweat others avoid is the taste of your success."],
    ["Discipline is choosing what you want most over what you want now.", "अनुशासन यानी अभी की चाहत पर असली चाहत को चुनना।"],
    ["हार का डर जीत से बड़ा नहीं होना चाहिए।", "The fear of losing should never be bigger than the will to win."],
    ["Kismat mehnat karne walon ki ghulam hai.", "Destiny is a servant of those who work hard."],
    ["अपनी कहानी का हीरो खुद बनो, किसी और की कहानी का किरदार मत बनो।", "Be the hero of your own story, not a character in someone else's."],
    ["Great things never came from comfort zones.", "महान चीज़ें आराम के घेरे से कभी नहीं निकलीं।"],
    ["जितना कठिन रास्ता, उतनी खूबसूरत मंज़िल।", "The harder the path, the more beautiful the destination."],
    ["Aaj thoda, kal thoda aur — bas yahi success ka mantra hai.", "A little today, a little more tomorrow—that's the mantra of success."],
    ["खुद को इतना मजबूत बनाओ कि हालात सलाम करें।", "Make yourself so strong that circumstances salute you."],
    ["Winners are not born, they are built — daily.", "विजेता पैदा नहीं होते, रोज़ बनाए जाते हैं।"],
    ["मुश्किल वक़्त में जो साथ दे, वो हौसला होता है।", "What stands by you in hard times is courage."],
    ["Stop doubting yourself, start doing.", "खुद पर शक करना बंद करो, करना शुरू करो।"],
    ["जो आज मुश्किल लगता है, कल वही तुम्हारी ताकत होगा।", "What feels hard today will be your strength tomorrow."],
    ["Mehnat kabhi bekaar nahi jaati, bas result late aata hai.", "Hard work never goes to waste; results just come late."],
    ["अपनी तुलना कल के खुद से करो, दूसरों से नहीं।", "Compare yourself with yesterday's you, not with others."],
    ["The best time to start was yesterday. The next best time is now.", "शुरुआत का सबसे अच्छा वक़्त कल था; दूसरा सबसे अच्छा अभी है।"],
    ["सपने सच तब होते हैं जब नींद छूटती है।", "Dreams come true when sleep is sacrificed."],
    ["Focus on progress, not perfection.", "परफेक्शन नहीं, प्रोग्रेस पर ध्यान दो।"],
    ["हौसला बुलंद हो तो रास्ते खुद बन जाते हैं।", "When courage is high, paths build themselves."],
    ["Your future is created by what you do today, not tomorrow.", "तुम्हारा भविष्य आज के काम से बनता है, कल के इंतज़ार से नहीं।"],
    ["गिरना इंसान की फितरत है, उठना विजेता की।", "Falling is human nature; rising is a winner's."],
    ["Kaam aisa karo ki log tumse prerna lein, salah nahi.", "Work so well that people take inspiration from you, not give advice."],
    ["जो खुद को बदल लेता है, वो दुनिया बदल देता है।", "One who changes himself changes the world."],
    ["No shortcuts, no excuses — sirf mehnat.", "No shortcuts, no excuses—just hard work."],
    ["मंज़िल दूर है तो क्या हुआ, चलना तो शुरू करो।", "So what if the goal is far? Just start walking."],
    ["Believe in yourself and you're halfway there.", "खुद पर भरोसा करो — आधा रास्ता वहीं पूरा हो जाता है।"],
    ["आज का पसीना, कल का सम्मान है।", "Today's sweat is tomorrow's respect."],
    ["Ek din sab theek hoga — bas tab tak himmat mat haarna.", "One day everything will be fine—just don't lose courage till then."],
  ],
  Sad: [
    ["मुस्कुराते चेहरे के पीछे भी दर्द होता है।", "Behind smiling faces, there's pain too."],
    ["Some goodbyes are never said, just felt.", "Kuch alvida kahe nahi jaate, bas mehsoos hote hain."],
    ["Yaadein bhi ajeeb hain, rula ke hasa deti hain.", "Memories make you cry, then smile."],
    ["मैं ठीक हूँ — सबसे बड़ा झूठ।", "'I'm fine'—the biggest lie."],
    ["Silence hurts most when you expected a conversation.", "खामोशी सबसे ज़्यादा तब चुभती है जब बात की उम्मीद हो।"],
    ["कुछ रिश्ते वक़्त से नहीं, एहसास से टूटते हैं।", "Some relationships break not from time, but from fading feelings."],
    ["Hans ke chhupa liya maine apna dard, kyunki duniya tamasha banati hai.", "I hid my pain behind a smile, because the world makes a spectacle of it."],
    ["जो अपने थे, वही पराये हो गए।", "Those who were mine became strangers."],
    ["Tears are words the heart can't say.", "आँसू वो शब्द हैं जो दिल कह नहीं पाता।"],
    ["अब आदत हो गई है अकेलापन की, शायद यही मेरी मंज़िल है।", "I've grown used to loneliness; maybe that's my destination."],
    ["Log kehte hain waqt sab bhula deta hai, par waqt ne sirf saunp diya dard.", "People say time heals everything, but time just handed me the pain."],
    ["मुस्कुराहट के पीछे छुपा दर्द कोई नहीं देखता।", "No one sees the pain hidden behind a smile."],
    ["Kuch log dil mein reh jaate hain, zindagi mein nahi.", "Some people stay in the heart, not in life."],
    ["उम्मीदें जितनी बड़ी होती हैं, टूटने की आवाज़ उतनी तेज़ होती है।", "The bigger the hope, the louder it breaks."],
    ["I smiled because I had no strength left to explain.", "मैं मुस्कुराया क्योंकि समझाने की ताकत नहीं बची थी।"],
    ["जिनसे सबसे ज़्यादा उम्मीद थी, उन्हीं ने सबसे ज़्यादा दर्द दिया।", "Those I hoped the most from hurt me the most."],
    ["Akelapan bura nahi hai, galat logon ke saath hona bura hai.", "Loneliness isn't bad; being with the wrong people is."],
    ["दिल टूटा है, पर धड़कना नहीं छोड़ा।", "The heart is broken, but it hasn't stopped beating."],
    ["Kash kisi ne poocha hota — 'tum theek ho?' sach mein.", "I wish someone had truly asked—'are you okay?'"],
    ["रातों को रोना भी एक तरह की आदत बन गई है।", "Crying at night has become a kind of habit."],
    ["Some goodbyes are never said, they are just felt.", "कुछ अलविदा कभी कहे नहीं जाते, बस महसूस होते हैं।"],
    ["जो मेरा था, वो मेरा क्यों नहीं रहा?", "What was mine, why didn't it stay mine?"],
    ["Dard woh nahi jo dikhta hai, dard woh hai jo chhupaya jaata hai.", "Pain isn't what you see; it's what's hidden."],
    ["अब किसी से शिकायत नहीं, बस खुद से बातें हैं।", "No complaints to anyone now—just conversations with myself."],
    ["Broken hearts still beat, just quieter.", "टूटे दिल भी धड़कते हैं, बस थोड़ा धीरे।"],
    ["सब कुछ होते हुए भी कुछ नहीं है — यही ज़िंदगी है।", "Having everything yet having nothing—that's life."],
    ["Yaadein woh mehmaan hain jo bina bulaye aati hain aur jaati nahi.", "Memories are guests that arrive uninvited and never leave."],
    ["मैं ठीक हूँ — ये दो शब्द सबसे बड़ा झूठ हैं।", "'I'm fine'—these two words are the biggest lie."],
    ["Sometimes the person you'd take a bullet for is the one behind the trigger.", "कभी-कभी जिसके लिए जान दे दो, वही जख्म देता है।"],
    ["अपनों ने जो जख्म दिए, वो दवा से नहीं भरते।", "Wounds given by loved ones don't heal with medicine."],
    ["Dil tootne ki awaaz kisi ko nahi sunai deti.", "No one hears the sound of a breaking heart."],
    ["खोया हुआ वक़्त नहीं, खोए हुए लोग याद आते हैं।", "It's not lost time I miss—it's lost people."],
    ["I'm tired of being strong all the time.", "हर वक़्त मजबूत रहने से थक गया हूँ।"],
    ["जिसे अपना समझा, उसी ने अकेला छोड़ दिया।", "The one I considered my own left me alone."],
    ["Aansu bhi thak gaye hain bahne se, ab bas khamoshi hai.", "Even tears are tired of flowing; now there's just silence."],
    ["कुछ रिश्ते साँसों जैसे होते हैं — छूटते हैं तो जीना मुश्किल हो जाता है।", "Some bonds are like breath—when they break, living gets hard."],
    ["Zakhm bharte hain, nishaan reh jaate hain.", "Wounds heal; scars remain."],
    ["मैंने सबको खुश रखा, और खुद को खो दिया।", "I kept everyone happy and lost myself."],
    ["The hardest goodbyes are the ones never explained.", "सबसे कठिन अलविदा वो होते हैं जिनकी कोई वजह नहीं बताई जाती।"],
    ["अब लोगों से उम्मीद रखना छोड़ दिया है, दर्द कम होता है।", "I've stopped expecting from people; it hurts less."],
    ["Raat bhar jaagna ab aadat hai, kyunki neend bhi saath chhod gayi.", "Staying awake all night is a habit now—even sleep left me."],
    ["कुछ लोग ज़िंदगी से जाते हैं, पर यादों से कभी नहीं।", "Some people leave your life but never your memories."],
    ["Dukh banta nahi jaata, sirf saja liya jaata hai.", "Pain can't be shared—only decorated."],
    ["I trusted too much, and that was my mistake.", "मैंने बहुत भरोसा किया — और वही मेरी गलती थी।"],
    ["जो कभी सब कुछ था, आज कुछ भी नहीं है।", "What was once everything is nothing today."],
    ["Akele the, akele hain, akele hi rahenge — shayad yahi likha hai.", "Was alone, am alone, will stay alone—maybe that's what's written."],
    ["दिल की बात लफ़्ज़ों तक आते-आते रुक जाती है।", "The heart's words stop before reaching the lips."],
    ["Some nights, the moon is my only company.", "कुछ रातों में चाँद ही मेरा एकमात्र साथी है।"],
    ["मुस्कान मेरी मजबूरी है, खुशी नहीं।", "My smile is a compulsion, not happiness."],
    ["Jis din main chup ho gaya, samajh jaana main toot gaya.", "The day I go silent, know that I've broken."],
    ["उम्मीदों का घर बसाया था, किस्मत ने जला दिया।", "I built a home of hopes; destiny burned it down."],
    ["It's hard to forget someone who gave you so much to remember.", "जिसने इतनी यादें दी हों, उसे भूलना मुश्किल है।"],
    ["अब किसी का इंतज़ार नहीं करता, इंतज़ार भी थक गया।", "I wait for no one now—even waiting got tired."],
    ["Dard ka izhaar bhi ab sirf status tak mehdoos hai.", "Even the expression of pain is now limited to a status."],
    ["खुद से मिलने का वक़्त निकालो, दुनिया से थक गए होगे।", "Take time to meet yourself—you must be tired of the world."],
    ["Goodbye is just a word until it happens to you.", "अलविदा बस एक शब्द है, जब तक तुम्हारे साथ न हो।"],
  ],
  Life: [
    ["ज़िंदगी छोटी नहीं, हम जीना देर से शुरू करते हैं।", "Life isn't short; we simply start living too late."],
    ["Life is 10% what happens to you, 90% how you react.", "ज़िंदगी 10% वो है जो होता है, 90% वो है जो तुम कैसे रिएक्ट करते हो।"],
    ["हर दिन एक नया पन्ना है, कहानी तुम्हारी है।", "Every day is a new page; the story is yours."],
    ["Zindagi mein sab kuch perfect nahi hota, par kuch kuch khaas zaroor hota hai.", "Not everything in life is perfect, but some things are truly special."],
    ["जो बीत गया उसे सबक बनाओ, बोझ नहीं।", "Turn the past into a lesson, not a burden."],
    ["Life doesn't give you what you want, it gives you what you need.", "ज़िंदगी वो नहीं देती जो तुम चाहते हो, वो देती है जो तुम्हें चाहिए।"],
    ["वक़्त बदलते देर नहीं लगती, बस बदलाव की शुरुआत चाहिए।", "Time doesn't take long to change; it just needs a beginning."],
    ["Zindagi ek kitab hai — kuch panne hansne ke, kuch rone ke.", "Life is a book—some pages for laughing, some for crying."],
    ["जीने का मज़ा तब है जब शर्तें खुद की हों।", "Life is fun when the terms are your own."],
    ["Enjoy the little things, for one day you may look back and realize they were the big things.", "छोटी-छोटी खुशियाँ जीयो — एक दिन वही सबसे बड़ी लगेंगी।"],
    ["ज़िंदगी में गिरना भी ज़रूरी है, तभी उठने का मज़ा आता है।", "Falling in life is necessary—only then is rising fun."],
    ["Har subah ek naya mauka hai, use barbaad mat karo.", "Every morning is a new chance; don't waste it."],
    ["जो लोग हँसते हैं, उनके भी दर्द होते हैं — बस छुपाना आता है।", "Even those who laugh have pain—they just know how to hide it."],
    ["Life is too short for regrets.", "ज़िंदगी पछतावों के लिए बहुत छोटी है।"],
    ["वक़्त से पहले और किस्मत से ज़्यादा किसी को कुछ नहीं मिलता।", "No one gets anything before time or beyond destiny."],
    ["Zindagi ka asli sukh cheezon mein nahi, logon mein hai.", "Life's real happiness isn't in things, it's in people."],
    ["हर मुश्किल के बाद एक आसानी छुपी होती है।", "Behind every difficulty hides an ease."],
    ["Live today like there's no tomorrow.", "आज को ऐसे जीयो जैसे कल हो ही नहीं।"],
    ["ज़िंदगी में सबसे बड़ा धन — सुकून है।", "The greatest wealth in life is peace."],
    ["Kuch rishtey waqt ke saath gehre hote hain, kuch waqt ke saath khatam.", "Some bonds deepen with time; some end with it."],
    ["जो कल का इंतज़ार करते हैं, वो आज खो देते हैं।", "Those who wait for tomorrow lose today."],
    ["Life is a journey, not a destination.", "ज़िंदगी एक सफर है, मंज़िल नहीं।"],
    ["हर दर्द एक सीख है, हर सीख एक ताकत।", "Every pain is a lesson, every lesson a strength."],
    ["Zindagi mein do cheezein kabhi mat bhoolo — maa ka pyaar aur apna maqsad.", "Never forget two things in life—a mother's love and your purpose."],
    ["बदलाव ज़िंदगी का एकमात्र नियम है।", "Change is the only rule of life."],
    ["The purpose of life is a life of purpose.", "ज़िंदगी का मकसद एक मकसद भरी ज़िंदगी है।"],
    ["जो आज है वो कल नहीं रहेगा — इसीलिए आज जी लो।", "What is today won't be tomorrow—so live today."],
    ["Zindagi mein sabse bada risk? Koi risk na lena.", "The biggest risk in life? Taking no risk at all."],
    ["हँसी मुफ्त की दवा है, रोज़ लो।", "Laughter is free medicine—take it daily."],
    ["Life becomes easier when you delete the unnecessary people.", "ज़िंदगी आसान हो जाती है जब गैर-ज़रूरी लोगों को हटा दो।"],
    ["हर अंधेरे के बाद उजाला आता है, बस इंतज़ार की हिम्मत चाहिए।", "Light comes after every darkness; you just need the courage to wait."],
    ["Zindagi mein jeet haar se nahi, seekhne se milti hai.", "Victory in life comes not from winning, but from learning."],
    ["अपनी ज़िंदगी के डायरेक्टर खुद बनो, एक्टर नहीं।", "Be the director of your own life, not just an actor."],
    ["Do what makes your soul shine.", "वो करो जिससे तुम्हारी रूह चमके।"],
    ["ज़िंदगी एक बार मिली है, इसे दूसरों के हिसाब से मत जीयो।", "You get one life—don't live it by others' rules."],
    ["Waqt hi sabse bada sikshak hai, aur sabse kathor bhi.", "Time is the greatest teacher—and the strictest one too."],
    ["हर दिन ज़िंदगी का पहला दिन समझकर जीयो।", "Live every day as if it's the first day of your life."],
    ["Life is simple, we insist on making it complicated.", "ज़िंदगी सीधी है, हम ही उसे उलझाते हैं।"],
    ["जिसने खुद को पहचान लिया, उसने ज़िंदगी पहचान ली।", "One who knows himself knows life."],
    ["Zindagi ka matlab sirf saans lena nahi, jazbaa jhelna bhi hai.", "Life isn't just breathing—it's feeling too."],
    ["छोटी-छोटी खुशियों का इकट्ठा खजाना ही ज़िंदगी है।", "A treasure of small joys—that's life."],
    ["Don't count the days, make the days count.", "दिन मत गिनो, दिनों को कीमती बनाओ।"],
    ["ज़िंदगी में कोई भी मोड़ आखिरी नहीं होता।", "No turn in life is ever the last one."],
    ["Har pal kimti hai, kyunki waqt wapas nahi aata.", "Every moment is precious because time never returns."],
    ["ज़िंदगी एक आईना है — जैसा दिखाओगे, वैसा दिखेगा।", "Life is a mirror—it shows what you show it."],
    ["Sabr rakho, waqt apna kaam karega.", "Be patient; time will do its work."],
    ["जीवन में संतुलन ही असली कला है।", "Balance is the true art of living."],
    ["Life is not about finding yourself, it's about creating yourself.", "ज़िंदगी खुद को ढूँढने का नाम नहीं, खुद को बनाने का नाम है।"],
    ["जो दिया उसमें खुश रहो, जो चाहिए उसके लिए मेहनत करो।", "Be happy with what you have; work for what you want."],
    ["Zindagi mein kuch bhi permanent nahi — na dukh, na sukh.", "Nothing in life is permanent—neither sorrow nor joy."],
    ["हर सुबह ज़िंदगी का दूसरा मौका है।", "Every morning is life's second chance."],
    ["Jiyo apni sharton par, maro apni marzi se — yahi zindagi hai.", "Live on your terms—that's life."],
  ],
  Friends: [
    ["कुछ दोस्त परिवार नहीं होते, फिर भी परिवार से कम नहीं होते।", "Some friends aren't family, yet they mean no less than family."],
    ["Dosti mein koi hisaab nahi hota, sirf ehsaas hota hai.", "In friendship there are no calculations—only feelings."],
    ["दोस्त वो नहीं जो साथ चले, दोस्त वो है जो साथ न छोड़े।", "A friend isn't one who walks with you, but one who never leaves your side."],
    ["Real friends don't count favors, they count memories.", "सच्चे दोस्त एहसान नहीं, यादें गिनते हैं।"],
    ["यारी में जुगाड़ भी प्यारा लगता है।", "Even the chaos feels lovely in friendship."],
    ["Dost woh hain jo tumhari khamoshi bhi samajh jaayein.", "Friends are those who understand even your silence."],
    ["दोस्ती का कोई त्यौहार नहीं होता, हर दिन त्यौहार होता है।", "Friendship has no single festival—every day is one."],
    ["Bachpan ke dost, zindagi bhar ki daulat.", "Childhood friends are a lifetime's treasure."],
    ["एक सच्चा दोस्त सौ रिश्तेदारों से बेहतर है।", "One true friend is better than a hundred relatives."],
    ["Friends who laugh together, stay together.", "जो साथ हँसते हैं, वो साथ रहते हैं।"],
    ["दोस्ती में दूरी नहीं, दिल की नज़दीकी मायने रखती है।", "In friendship, it's not distance but closeness of hearts that matters."],
    ["Yaarana woh rishta hai jo khoon se nahi, karam se banta hai.", "Friendship is a bond made not by blood but by deeds."],
    ["दोस्त वो चम्कीले सितारे हैं जो अंधेरे में साथ चलते हैं।", "Friends are those bright stars that walk with you in the dark."],
    ["Squad goals: saath jeena, saath marna, saath hasna.", "Squad goals: live together, laugh together, stay together."],
    ["दोस्ती का मतलब — बिना कहे सब समझना।", "Friendship means understanding everything without a word."],
    ["True friends are never apart, maybe in distance but never in heart.", "सच्चे दोस्त कभी अलग नहीं होते — दूरी में हों, दिल में नहीं।"],
    ["मेरे दोस्त मेरी गलतियों के गवाह और मेरी जीत के साथी हैं।", "My friends are witnesses to my mistakes and partners in my wins."],
    ["Dosti ki sabse badi nishani — bina wajah ka hasna.", "The biggest sign of friendship—laughing for no reason."],
    ["जो बुरे वक़्त में साथ खड़ा हो, वही असली दोस्त है।", "The one who stands by you in bad times is the real friend."],
    ["Friends are the family we choose.", "दोस्त वो परिवार है जिसे हम खुद चुनते हैं।"],
    ["यारी में शर्तें नहीं होतीं, शर्त लगा दो तो सौदा हो जाता है।", "Friendship has no conditions; add conditions and it becomes a deal."],
    ["Doston ke saath waqt nahi, pal ginne chahiye.", "With friends, count moments, not time."],
    ["दोस्ती एक ऐसा बैंक है जहाँ यादें जमा होती हैं।", "Friendship is a bank where memories are deposited."],
    ["Masti, magajmari aur dosti — yahi meri zindagi hai.", "Fun, madness, and friendship—that's my life."],
    ["जो दोस्त हँसी में साथ दे और रोने में कंधा, वो रखना ज़िंदगी भर।", "Keep forever the friend who joins your laughter and lends a shoulder in tears."],
    ["Friendship isn't about who came first, it's about who never left.", "दोस्ती इस बारे में नहीं कि कौन पहले आया, बल्कि कौन कभी गया नहीं।"],
    ["मेरे दोस्तों के बिना मेरी कहानी अधूरी है।", "My story is incomplete without my friends."],
    ["Dost kam ho toh chalega, par sacche hone chahiye.", "Few friends are fine, as long as they're true."],
    ["दोस्ती में 'मैं' नहीं, 'हम' बोला जाता है।", "In friendship, we say 'we', not 'I'."],
    ["Life was meant for good friends and great adventures.", "ज़िंदगी अच्छे दोस्तों और बड़े कारनामों के लिए बनी है।"],
    ["दोस्तों के साथ हर मुश्किल रास्ता आसान लगता है।", "With friends, every hard road feels easy."],
    ["Ek pakka dost, hazaar kamzor rishton se behtar hai.", "One solid friend beats a thousand weak connections."],
    ["दोस्ती की कोई भाषा नहीं होती, सिर्फ एहसास होता है।", "Friendship has no language—only feeling."],
    ["Friends make the good times better and the hard times easier.", "दोस्त अच्छे वक़्त को बेहतर और बुरे वक़्त को आसान बनाते हैं।"],
    ["मेरे यार मेरा गर्व हैं, मेरी ताकत हैं।", "My friends are my pride and my strength."],
    ["Dosti mein umar, status, paisa — kuch nahi dekha jaata.", "In friendship, age, status, money—nothing matters."],
    ["जिनके साथ हँसी रुकती नहीं, वही मेरे दोस्त हैं।", "The ones with whom laughter never stops—those are my friends."],
    ["A friend is one soul in two bodies.", "दोस्त यानी दो शरीरों में एक रूह।"],
    ["दोस्ती का रिश्ता दिल से जुड़ता है, मोबाइल से नहीं।", "The bond of friendship connects through hearts, not phones."],
    ["Yaari bina filter ki hoti hai — jaisi hai, waisi hi.", "Friendship comes without filters—as it is, so it stays."],
    ["दोस्तों के साथ बिताया हर पल, ज़िंदगी का बोनस है।", "Every moment with friends is a bonus of life."],
    ["Side by side or miles apart, real friends are always close to the heart.", "साथ हों या मीलों दूर, सच्चे दोस्त हमेशा दिल के करीब होते हैं।"],
    ["दोस्ती में माफी माँगना नहीं पड़ता, बस एक हँसी काफी है।", "In friendship you don't need apologies—one laugh is enough."],
    ["Meri gang meri jaan hai.", "My gang is my life."],
    ["दोस्त वो हैं जो तुम्हारी कमियों को भी प्यार से ढक लेते हैं।", "Friends are those who lovingly cover even your flaws."],
    ["Good friends are like stars — you don't always see them, but you know they're there.", "अच्छे दोस्त सितारों जैसे होते हैं — हमेशा नहीं दिखते, पर होते ज़रूर हैं।"],
    ["दोस्ती सबसे सुंदर रिश्ता है, क्योंकि इसमें कोई मजबूरी नहीं होती।", "Friendship is the most beautiful bond because it has no compulsion."],
    ["Doston ke bina toh party bhi adhuri hai.", "Without friends, even a party feels incomplete."],
    ["जो दोस्त सच बोलकर नाराज़ कर दे, वो सबसे सच्चा है।", "The friend who upsets you with the truth is the truest one."],
    ["Friends forever, tension never.", "दोस्त हमेशा के लिए, टेंशन कभी नहीं।"],
    ["दोस्ती में दिए गए वादे नहीं, दिए गए पल याद रहते हैं।", "In friendship, it's not the promises but the moments that are remembered."],
    ["Yeh dosti hum nahi todenge — chahe zamaana saath chhod de.", "This friendship we won't break—even if the world leaves our side."],
  ],
  "Single/Breakup": [
    ["Single, peaceful, and no longer explaining my worth.", "अकेला हूँ, सुकून में हूँ, और अब अपनी कीमत नहीं समझाता।"],
    ["कुछ रिश्ते टूटना ही बेहतर होता है, जुड़े रहने से।", "Some relationships are better broken than held together."],
    ["Main akela hoon, lekin kamzor nahi — bas ab khud ka hoon.", "I'm alone but not weak—I'm just my own now."],
    ["टूटकर भी बिकरना नहीं आता मुझे।", "Even broken, I don't know how to fall apart."],
    ["Single by choice, not by chance.", "अकेला अपनी मर्ज़ी से, किस्मत से नहीं।"],
    ["जो छोड़कर गया, उसका शुक्रिया — खुद को पा लिया।", "Thanks to the one who left—I found myself."],
    ["Breakup ne toda zaroor, par jodna bhi sikha diya.", "The breakup broke me, but also taught me to rebuild."],
    ["अब किसी के इंतज़ार में नहीं, अपनी राह में हूँ।", "Not waiting for anyone anymore—I'm on my own path."],
    ["Being single is not a status, it's a superpower.", "सिंगल होना कोई स्टेटस नहीं, एक सुपरपावर है।"],
    ["जिस रिश्ते में सुकून न हो, वहाँ टिकना मुर्खी है।", "Staying in a relationship without peace is foolishness."],
    ["Alone time is when I recharge, not when I cry.", "अकेले का वक़्त मेरा चार्जिंग टाइम है, रोने का नहीं।"],
    ["उसके जाने से ज़िंदगी रुकी नहीं, बस रास्ता बदल गया।", "Life didn't stop when they left—the path just changed."],
    ["Single life: no drama, no trauma, only sukoon.", "Single life: no drama, no trauma, only peace."],
    ["मैंने खुद को चुनना सीख लिया, बस यही काफी है।", "I've learned to choose myself—that's enough."],
    ["Some people leave, and that's the gift.", "कुछ लोग चले जाते हैं — और वही तोहफा होता है।"],
    ["टूटे दिल ने सिखाया — खुद से प्यार सबसे पहले।", "A broken heart taught me—love yourself first."],
    ["Not single, not taken — just on my own journey.", "न सिंगल, न कमिटेड — बस अपने सफर पर हूँ।"],
    ["जो मेरा नहीं हो सका, वो कभी मेरा था ही नहीं।", "What couldn't be mine was never mine."],
    ["Self-love is the best love story.", "खुद से मोहब्बत सबसे अच्छी लव स्टोरी है।"],
    ["उसके बिना भी हँसना आ गया, यही मेरी जीत है।", "I learned to smile without them—that's my victory."],
    ["Single hai, par settle nahi kiya kisi galat ke saath.", "Single, but never settled with the wrong person."],
    ["दिल टूटा, पर हौसला नहीं।", "The heart broke, but not the courage."],
    ["I'd rather be alone than with the wrong person.", "गलत इंसान के साथ रहने से अकेला रहना बेहतर है।"],
    ["जाने दिया उसे, क्योंकि रोकना मजबूरी होती, मोहब्बत नहीं।", "I let them go, because holding on is compulsion, not love."],
    ["Single and shining — no dimming my light for anyone.", "सिंगल और चमकता हुआ — किसी के लिए अपनी रोशनी नहीं बुझाऊँगा।"],
    ["ब्रेकअप एक अंत नहीं, एक नई शुरुआत है।", "A breakup isn't an end—it's a new beginning."],
    ["Meri khushi ab kisi pe depend nahi karti.", "My happiness no longer depends on anyone."],
    ["जो चला गया, वो सबक बन गया।", "Whoever left became a lesson."],
    ["Healing in progress — please don't disturb.", "जख्म भर रहे हैं — कृपया परेशान न करें।"],
    ["अब मैं अपनी खुद की प्राथमिकता हूँ।", "Now I am my own priority."],
    ["Single life is not a waiting room, it's a whole world.", "सिंगल लाइफ कोई वेटिंग रूम नहीं, एक पूरी दुनिया है।"],
    ["उसे भूलना मुश्किल था, पर खुद को पाना ज़रूरी था।", "Forgetting them was hard, but finding myself was necessary."],
    ["No relationship, no tension — bas me, myself and I.", "No relationship, no tension—just me, myself and I."],
    ["टूटने के बाद जो बनता है, वो पहले से मजबूत होता है।", "What forms after breaking is stronger than before."],
    ["I'm not heartless, I just learned to use my heart less.", "मैं बेदर्द नहीं हूँ, बस दिल कम इस्तेमाल करना सीख लिया।"],
    ["अकेले चलना सीख लिया, अब साथी की तलाश नहीं।", "I learned to walk alone; I'm not searching for a companion anymore."],
    ["Breakup ke baad ka glow-up alag hi level ka hota hai.", "The post-breakup glow-up hits different."],
    ["खुद के साथ रहना सबसे सच्चा रिश्ता है।", "Being with yourself is the truest relationship."],
    ["Single is not lonely, single is free.", "सिंगल अकेला नहीं, आज़ाद होता है।"],
    ["जो निकल गया, उसे लौटने की जगह नहीं बची।", "Whoever walked out has no space left to return to."],
    ["My standards went up the day they walked out.", "जिस दिन वो गए, मेरे स्टैंडर्ड ऊँचे हो गए।"],
    ["अब रिश्ते नहीं, सिर्फ मेरे सपने मेरे साथी हैं।", "No relationships now—only my dreams are my companions."],
    ["Closure? Maine khud de diya khud ko.", "Closure? I gave it to myself."],
    ["दिल का दरवाज़ा बंद नहीं किया, बस अब चाबी सोच-समझकर देता हूँ।", "I didn't close my heart's door—I just hand over the key wisely now."],
    ["Single, strong, and silently winning.", "सिंगल, मजबूत, और चुपचाप जीतता हुआ।"],
    ["उसके बिना की ज़िंदगी, उसके साथ से ज़्यादा खूबसूरत है।", "Life without them is more beautiful than it was with them."],
    ["Lost them, found me — fair deal.", "उन्हें खोया, खुद को पाया — सही सौदा।"],
    ["अब कोई मुझे तोड़ नहीं सकता, क्योंकि मैं खुद जुड़ चुका हूँ।", "No one can break me now, because I've put myself back together."],
    ["Single by experience, wise by choice.", "तजुर्बे से सिंगल, समझदारी से खुश।"],
    ["जिसने छोड़ा, उसे छोड़ दो — जिसने सिखाया, उसे याद रखो।", "Let go of who left; remember what they taught."],
    ["Meri akelepan meri azaadi hai.", "My solitude is my freedom."],
    ["अब मैं किसी का इंतज़ार नहीं करता, मैं अपना इंतज़ाम करता हूँ।", "I don't wait for anyone anymore—I make my own arrangements."],
  ],
  "Daily Quotes": [
    ["हर सुबह एक नया मौका है, खुद को बेहतर बनाने का।", "Every morning is a new chance to become better."],
    ["Start your day with gratitude, end it with pride.", "Din ki shuruaat shukr se, ant garv se."],
    ["आज का दिन कल से बेहतर होगा, बस यकीन रखो।", "Today will be better than yesterday—just believe."],
    ["Good morning! Chai, sapne aur thodi si mehnat.", "Tea, dreams and a little hard work."],
    ["छोटे कदम भी मंज़िल तक ले जाते हैं।", "Small steps also lead to the destination."],
    ["Be the reason someone smiles today.", "Aaj kisi ki muskaan ki wajah bano."],
    ["जो बीत गया उसे भूलो, जो आने वाला है उसे जीतो।", "Forget what's gone, win what's coming."],
    ["Aaj ka suvichar: shaant raho, sab theek hoga.", "Today's thought: stay calm, all will be well."],
    ["Don't count the days, make the days count.", "Din gino mat, dinon ko kaabil banao."],
    ["मुस्कुराहट सबसे सुंदर गहना है, रोज़ पहनो।", "A smile is the finest jewel—wear it daily."],
    ["Every sunrise is an invitation to begin again.", "Har suraj naye aaghaz ka nyota hai."],
    ["सोच अच्छी रखो, दिन अपने आप अच्छा होगा।", "Keep good thoughts and the day becomes good."],
    ["Aaj khud se ek promise karo — give up nahi karna.", "Promise yourself today: never give up."],
    ["Progress, not perfection.", "Behtar banna, perfect nahi."],
    ["समय और सब्र — दोनों सबसे बड़े शिक्षक हैं।", "Time and patience are the greatest teachers."],
    ["Your only competition is who you were yesterday.", "Tumhara muqabla sirf kal ke tumse hai."],
    ["रोज़ थोड़ा सीखो, रोज़ थोड़ा बढ़ो।", "Learn a little daily, grow a little daily."],
    ["Positive mind, positive vibes, positive life.", "Sakaratmak soch, sakaratmak zindagi."],
    ["Kal ki chinta chhodo, aaj ko jee bhar ke jiyo.", "Leave tomorrow's worry, live today fully."],
    ["Discipline today, freedom tomorrow.", "Aaj anushasan, kal azaadi."],
    ["जिंदगी आसान नहीं होती, उसे आसान बनाना पड़ता है।", "Life isn't easy; you have to make it easy."],
    ["Kindness costs nothing but means everything.", "Dayalu hona muft hai, par anmol hai."],
    ["हर दिन अपने सपनों की तरफ़ एक कदम बढ़ाओ।", "Take one step toward your dreams every day."],
    ["Wake up with determination, sleep with satisfaction.", "Iraade se utho, sukoon se so jao."],
    ["Aaj ka din tumhara hai — isse yaadgaar banao.", "Today is yours—make it memorable."],
    ["शुक्रिया कहना सीखो, ज़िंदगी खूबसूरत लगेगी।", "Learn to say thanks; life will feel beautiful."],
    ["Little by little, a little becomes a lot.", "Thoda thoda karke bahut ho jata hai."],
    ["Believe you can and you're halfway there.", "Yakeen karo, aadha safar poora."],
    ["मन साफ़ हो तो हर दिन त्योहार है।", "With a clear heart, every day is a festival."],
    ["Do something today your future self will thank you for.", "Aaj woh karo jiske liye kal ka tum shukriya kahe."],
    ["Subah ki chai aur positive soch — perfect combo.", "Morning tea and positive thoughts—perfect combo."],
    ["Stay humble, work hard, be kind.", "Vinamra raho, mehnat karo, dayalu bano."],
    ["गलतियाँ बताती हैं कि आप कोशिश कर रहे हैं।", "Mistakes show you're trying."],
    ["Today is a good day to have a good day.", "Aaj achha din banane ka achha din hai."],
    ["Khud par bharosa hi sabse bada hathiyar hai.", "Self-belief is the biggest weapon."],
    ["Make today so awesome that yesterday gets jealous.", "Aaj itna shaandar banao ki kal jal jaaye."],
    ["हर रात के बाद सवेरा ज़रूर आता है।", "After every night, morning surely comes."],
    ["Focus on the good, it grows.", "Achhai par dhyan do, woh badhti hai."],
    ["Rozana ek naya sabak, ek nayi shuruaat.", "A new lesson and a new start every day."],
    ["Health is wealth — pani piyo, walk karo, khush raho.", "Health is wealth—drink water, walk, stay happy."],
    ["मेहनत का फल देर से मिलता है, पर मीठा मिलता है।", "Hard work pays late but sweet."],
    ["Be a voice, not an echo.", "Awaaz bano, goonj nahi."],
    ["Aaj kuch naya try karo, dar ko hara do.", "Try something new today and defeat fear."],
    ["Peace begins with a smile.", "Shanti ek muskaan se shuru hoti hai."],
    ["अच्छे लोगों के साथ रहो, अच्छा बन जाओगे।", "Stay with good people and you'll become good."],
    ["Choose joy, every single day.", "Har din khushi chuno."],
    ["Sapne woh nahi jo neend mein aayein, woh hain jo sone na dein.", "Dreams are what don't let you sleep."],
    ["Good things take time.", "Achhi cheezon mein waqt lagta hai."],
    ["आज का विचार: खुद से प्यार करो, बाकी सब बाद में।", "Today's thought: love yourself first."],
    ["Your vibe attracts your tribe.", "Tumhari vibe tumhare log laati hai."],
    ["Har din ek tohfa hai, isliye ise present kehte hain.", "Every day is a gift, that's why it's called the present."],
    ["Keep going. Everything you need will come to you.", "Chalte raho, sab milega."],
  ],
};
